### ISSUE TITLE
Please update scipy version and other Python packages

### ISSUE THREAD

**Issue by EmmaNguyen** [eriklindernoren/Keras-GAN#10]
Hi Erik,

I am encountering a problem with `scipy` method named `imread`, which I believe it is deprecated followed the recent version `1.0.0`. Probably, this would work with earlier version such as `0.19.0` however, it still causes a lot of conflictions for Keras and Tensorflow.

I am using Ananconda with `Python 3.6.4`. Please see more detail as follows

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "cyclegan.py", line 244, in <module>
    gan.train(epochs=30000, batch_size=2, save_interval=200)
  File "cyclegan.py", line 161, in train
    imgs_A = self.data_loader.load_data(domain="A", batch_size=half_batch)
  File "/home/emma/Research/GAN/keras_GAN/Keras-GAN/cyclegan/data_loader.py", line 18, in load_data
    img = self.imread(img_path)
  File "/home/emma/Research/GAN/keras_GAN/Keras-GAN/cyclegan/data_loader.py", line 39, in imread
    return scipy.misc.imread(path, mode='RGB').astype(np.float)
AttributeError: module 'scipy.misc' has no attribute 'imread'
```
Thanks very much,

Emma

**Comment by eriklindernoren** [comment]
That's strange because `scipy.misc.imread` definitely exists in 1.0.0 (https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html). I'll look up the versions of my packages and get back to you.

**Comment by EmmaNguyen** [comment]
I believe it's belonged to Python 2.7, not Python 3x

I did try to install PIL by using Annaconda and all of the packages was
degraded to Python 2.7 ...


ᐧ

On Wed, Feb 28, 2018 at 8:27 PM, Erik Linder-Norén <notifications@github.com

**Comment by eriklindernoren** [comment]
Hi Emma,

Sorry for the late response. I have updated all my packages and I have no problem running the scripts even with the latest versions. In the following code snippet you can see that I can access `scipy.misc.imread` even with version 1.0.1 of scipy:

```python
Python 3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> print (scipy.__version__)
1.0.1
>>> from scipy.misc import imread
>>> 
```

Have you been able to solve this since you posted?

**Comment by SimonTreu** [comment]
Hi,
I had a similar issue. Apparently `imread` depends on Pillow (former PIL). You can install it with anaconda: 

> conda install pillow

see also the following [issue on StackOverflow](https://stackoverflow.com/questions/15345790/scipy-misc-module-has-no-attribute-imread)

**Comment by EmmaNguyen** [comment]
Thanks, @eriklindernoren, and @SimonTreu for your suggestion. I fixed this error sometimes ago but forgot to post it here. 

As far as I remember it was a series of minor changes with Python dependencies until finding out the right set of packages working together without warning or errors. PS: the better way is running through a docker, but in a research trying-and-failing phase, it is quite hard to make sure all you want is there.

Probably, this exhaustive list would help some other folks save time with `Ananconda`

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
absl-py=0.1.13=py36_0
alabaster=0.7.10=py36h306e16b_0
asn1crypto=0.24.0=py36_0
babel=2.5.3=py36_0
backcall=0.1.0=py36_0
backports=1.0=py36hfa02d7e_1
backports.weakref=1.0rc1=py36_0
bleach=1.5.0=py36_0
ca-certificates=2018.03.07=0
certifi=2018.1.18=py36_0
cffi=1.11.5=py36h9745a5d_0
chardet=3.0.4=py36h0f667ec_1
cryptography=2.2.2=py36h14c3975_0
cycler=0.10.0=py36h93f1223_0
dbus=1.13.2=h714fa37_1
decorator=4.3.0=py36_0
docutils=0.14=py36hb0f60f5_0
expat=2.2.5=he0dffb1_0
fontconfig=2.12.6=h49f89f6_0
freetype=2.8=hab7d2ae_1
glib=2.56.1=h000015b_0
gst-plugins-base=1.14.0=hbbd80ab_1
gstreamer=1.14.0=hb453b48_1
h5py=2.7.1=py36h3585f63_0
hdf5=1.10.1=h9caa474_1
html5lib=0.9999999=py36_0
icu=58.2=h9c2bf20_1
idna=2.6=py36h82fb2a8_1
imagesize=1.0.0=py36_0
intel-openmp=2018.0.0=8
ipython=6.3.1=py36_0
ipython_genutils=0.2.0=py36hb52b0d5_0
jedi=0.11.1=py36_1
jinja2=2.10=py36ha16c418_0
jpeg=9b=h024ee3a_2
keras=2.1.5=py36_0
kiwisolver=1.0.1=py36h764f252_0
libedit=3.1=heed3624_0
libffi=3.2.1=hd88cf55_4
libgcc-ng=7.2.0=hdf63c60_3
libgfortran-ng=7.2.0=hdf63c60_3
libpng=1.6.34=hb9fc6fc_0
libprotobuf=3.5.2=h6f1eeef_0
libstdcxx-ng=7.2.0=hdf63c60_3
libtiff=4.0.9=h28f6b97_0
libxcb=1.13=h1bed415_1
libxml2=2.9.8=hf84eae3_0
markdown=2.6.11=py36_0
markupsafe=1.0=py36hd9260cd_1
matplotlib=2.2.2=py36h0e671d2_1
mkl=2018.0.2=1
mkl_fft=1.0.1=py36h3010b51_0
mkl_random=1.0.1=py36h629b387_0
ncurses=6.0=h9df7e31_2
numpy=1.14.2=py36hdbf6ddf_1
numpydoc=0.8.0=py36_0
olefile=0.45.1=py36_0
openssl=1.0.2o=h20670df_0
packaging=17.1=py36_0
parso=0.1.1=py36h35f843b_0
pcre=8.42=h439df22_0
pexpect=4.5.0=py36_0
pickleshare=0.7.4=py36h63277f8_0
pillow=5.1.0=py36h3deb7b8_0
pip=9.0.3=py36_0
prompt_toolkit=1.0.15=py36h17d85b1_0
protobuf=3.5.2=py36hf484d3e_0
ptyprocess=0.5.2=py36h69acd42_0
pycparser=2.18=py36hf9f622e_1
pygments=2.2.0=py36h0d3125c_0
pyopenssl=17.5.0=py36h20ba746_0
pyparsing=2.2.0=py36hee85983_1
pyqt=5.9.2=py36h751905a_0
pysocks=1.6.8=py36_0
python=3.6.5=hc3d631a_0
python-dateutil=2.7.2=py36_0
pytz=2018.4=py36_0
pyyaml=3.12=py36hafb9ca4_1
qt=5.9.5=h7e424d6_0
readline=7.0=ha6073c6_4
requests=2.18.4=py36he2e5f8d_1
scipy=1.0.1=py36hfc37229_0
setuptools=39.0.1=py36_0
simplegeneric=0.8.1=py36_2
sip=4.19.8=py36hf484d3e_0
six=1.11.0=py36h372c433_1
snowballstemmer=1.2.1=py36h6febd40_0
sphinx=1.7.2=py36_0
sphinxcontrib=1.0=py36h6d0f590_1
sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
sqlite=3.22.0=h1bed415_0
tensorflow=1.5.0=0
tensorflow-base=1.5.0=py36hff88cb2_1
tensorflow-tensorboard=1.5.1=py36hf484d3e_0
tk=8.6.7=hc745277_3
tornado=5.0.1=py36_1
traitlets=4.3.2=py36h674d592_0
typing=3.6.4=py36_0
urllib3=1.22=py36hbe7ace6_0
wcwidth=0.1.7=py36hdf4376a_0
werkzeug=0.14.1=py36_0
wheel=0.31.0=py36_0
xz=5.2.3=h55aa19d_2
yaml=0.1.7=had09818_2
zlib=1.2.11=ha838bed_2 
```

**Comment by eriklindernoren** [comment]
I have added pillow to requirements.txt. Hopefully that solves this issue.

**Comment by sharajpanwar** [comment]
Hello Erik! Thanks for great work..!
I am trying DCGAN for my project. My discriminator is over fitting and generator loss is increasing. I am trying to update generator more often than discriminator, for it to get converged. Can you please suggest changes in code for that?
Thanks.!
