### ISSUE TITLE
Module 'scipy' has no attribute 'misc'

### ISSUE THREAD

**Issue by Amrouane** [eriklindernoren/Keras-GAN#201]
I'm getting the exception: `AttributeError: module 'scipy' has no attribute 'misc'`
My scipy version is 1.3.1
I gave it a a little bit o research and I found that `scipy.misc` is not only deprecated but removed entirely from `scipy`. Are there any alternatives for the `scipy.misc.imresize()` method that I can use instead of :
`X_train = np.array([scipy.misc.imresize(x, [self.img_rows, self.img_cols]) for x in X_train])`

**Comment by bw0248** [comment]
Seems to be working with scipy version 1.1.0
If you're using pip just do ```pip install scipy=1.1.0``` in your venv.

**Comment by Amrouane** [comment]
> Seems to be working with scipy version 1.1.0
> If you're using pip just do `pip install scipy==1.1.0` in your venv.
> I haven't validated results as of yet though.

Yes, that worked.

**Comment by saadsakib** [comment]
Hi, I'm getting this error in scipy version 1.6.1. I got this error for `scipy.misc.imsave(image_name, data)`. Any alternatives that I can use?
